### ISSUE TITLE
[BUG]: In module user: task to find user apparently tries to create the user

### ISSUE THREAD

**Issue by nikolisg7** [dell/ansible-powerscale#109]
**Describe the bug**
I am using a task identical to the example task from the user module to assess if a ADS user exists:
```
- name: Get User Details using user name
  dellemc.powerscale.user:
    onefs_host: "{{onefs_host}}"
    port_no: "{{port_no}}"
    api_user: "{{api_user}}"
    api_password: "{{api_password}}"
    verify_ssl: "{{verify_ssl}}"
    access_zone: "{{access_zone}}"
    provider_type: ads
    user_name: gavagai
    state: "present"
```
Upon execution I am receiving the following error:
```
FAILED! => {"changed": false, "msg": "Unable to create a user, 'password' is missing"}
```

**To Reproduce**
1. Create the task as above
2. Run the task on a cluster with configured ads 
Step n See error

**Expected behavior**
If user exists in zone: JSON response with user details, the ones returned from GET /platform/auth/users/USER
If user does not exist in zone: error response similar to the API:
```
{
"errors" : 
[

{
"code" : "AEC_NOT_FOUND",
"message" : "Failed to find user for 'USER:gavagai': No such user"
}
]
}
```

**Screenshots**

**Logs**
If applicable, submit logs or stack traces from the affected services

**System Information (please complete the following information):**
 - OS/Version: OneFS 9.7.1.0
 - Ansible Version 2.16.5
 - Python Version [e.g. 3.10.11]  
 - Powerscale Ansible Version: 3.2.0

**Additional context**
I wouldn't mind to use direct API queries to get user information, if the user module doesn't support it. Perhaps then the documentation/examples in the user module should be updated
