### ISSUE TITLE
[QUESTION]: Unable to fetch version of array error when running playbook

### ISSUE THREAD

**Issue by mcen1** [dell/ansible-powerscale#119]
Hello.

I'm helping a team automate some tasks on their Isilon systems. I'm just getting started using the playbook and I encountered this error:
```
TASK [rotate_certs : Import the new server certificate and set as default] ******************************************************************************************************************************

fatal: [localhost]: FAILED! => {"changed": false, "msg": "Unable to fetch version of array arrayname.company.com:********, failed with error: Failed to parse: [https://array.company.com:********:********/session/1/session](https://array.company.com:%2A%2A%2A%2A%2A%2A%2A%2A:********/session/1/session)"}
```

The system is an Isilon (the GUI says OneFS storage administration, version 9.7.0.0). When I go to the /session/1/session URL, I receive this: 
`{"message":""}`

I don't know what is missing or really expected of me, this is the very first time I'm interacting with this Ansible module.

Relevant code:
```
- name: Import the new server certificate and set as default
  dellemc.powerscale.server_certificate:
    onefs_host: "{{ storage_host }}"
    api_user: "{{ storage_username }}"
    api_password: "{{ storage_password }}"
    verify_ssl: false
    state: present
    alias_name: "{{ alias_name }}"
    certificate_path: "/ifs/something/{{ new_cert_name }}"
    certificate_key_path: "/ifs/something/something.key"
    is_default_certificate: true
```

isilon-sdk version is 0.3.0.1
