### ISSUE TITLE
[BUG]: Module filesystem not idempotent when creating directory and assign ACE

### ISSUE THREAD

**Issue by nikolisg7** [dell/ansible-powerscale#121]
**Describe the bug**
We have a task that uses the `filesystem` module to create a directory with `owner` and `group` and assign an ACE to it. The task runs and from what we can see on the OneFS filesystem afterwards, it creates the directory correctly. Upon re-execution of the task, it is still reported as `changed` though; since the `filesystem` module does not support diff mode, we are not sure what is supposed to have changed. A manual check on the OneFS filesystem doesn't seem to show any changes. For test purposes, we have the playbook end with this task, i.e. no subsequent tasks can interfere with propagated settings.

**To Reproduce**
Task looks like this:
```
- name: Powerscale Create Directories
  dellemc.powerscale.filesystem:
      onefs_host: "{{ ansible_host }}"
      port_no: "{{ powerscale_port }}"
      api_user: "{{ ps_admin }}"
      api_password: "{{ ps_admin_passwd }}"
      verify_ssl: "{{ verify_ssl }}"
      path: "{{ path }}"
      access_zone: "{{ access_zone }}"
      owner:
          name: "{{ user_name }}"
          provider_type: ads 
      group:
          name: "{{ group_name }}"
          provider_type: ads 
      access_control_rights: "{{ this_acl.0 }}"
      access_control_rights_state: add 
      recursive: false
      state: present
  delegate_to: "{{ powerscale_execution_host }}"
```
where `this_acl.0` is a dict representation of the `AclObject` 
**Expected behavior**
Expected behavior would be for the task to report OK (and not CHANGED) on re-execution (idempotency)

**Screenshots**

**Logs**
If applicable, submit logs or stack traces from the affected services

**System Information (please complete the following information):**
 - OS/Version: OneFS 7.1.0.2
 - Ansible Version: core 2.16.5
 - Python Version: 3.10.11
 - isilon-sdk: 0.3.0.1
 - dellemc.powerscale: 3.4.0

**Additional context**
