### ISSUE TITLE
[FEATURE]: dellemc.powerscale.group should also handle groups

### ISSUE THREAD

**Issue by bugmanch** [dell/ansible-powerscale#131]
Currently, dellemc.powerscale.group allows adding or removing a single user inside a group.

It shall also allow to add or remove a group inside the group.

For instance, I propose the following:

```
dellemc.powerscale.group
  users:
    - user_name: "{{user_name}}"
    - user_id: "{{user_id}}"
  groups:
    - group_name_ "{{another_group}}"
```

My objective: add an AD domain group in the local Administrators group of a newly created Access Zone
