### ISSUE TITLE
[BUG]: dellemc.powerscale.networkpool fails as Unauthorized

### ISSUE THREAD

**Issue by bugmanch** [dell/ansible-powerscale#133]
**Error description**
Role dellemc.powerscale.networkpool fails with following error message:

`fatal: [localhost]: FAILED! => {"changed": false, "msg": "Unable to get network pool pool0 failed with error: HTTP Error 401: Unauthorized "}`

**Environment details**
Occurs on:
- Ansible v. 2.16.11 and 2.17.5
- Python 3.10.12 and 3.12.3
- dellemc.powerscale 3.5 (was working with version 1.5)
- OneFS 9.7.1.2

**Code example**
```
    - name: Get Management IP Pool
      dellemc.powerscale.networkpool:
        onefs_host: "{{ pscale_host }}"
        api_user: "root"
        api_password: "{{ pscale_password }}"
        verify_ssl: false

        groupnet_name: "groupnet0"
        subnet_name: "subnet0"
        pool_name: "pool0"
        state: "present"
```

**Comment by anupamaloke** [comment]
@bugmanch, I just tried the below playbook and I was able to successfully get the details. Could you please check your username and password details or make sure that the user has the right privileges to gather the network pool details?

```
---
- hosts: powerscale
  gather_facts: no

  vars:
    onefs_creds: &onefs_creds
      onefs_host: "{{ inventory_hostname }}"
      api_user: "{{ user }}"
      api_password: "{{ password }}"
      verify_ssl: False

  tasks:
    - name: get network pool details
      dellemc.powerscale.info:
        <<: *onefs_creds
        gather_subset:
          - network_pools
      register: result
      delegate_to: localhost

    - name: get details about the first network pool
      dellemc.powerscale.networkpool:
        <<: *onefs_creds
        groupnet_name: "{{ result.NetworkPools[0].id.split('.')[0] }}"
        subnet_name: "{{ result.NetworkPools[0].id.split('.')[1] }}"
        pool_name: "{{ result.NetworkPools[0].id.split('.')[2] }}"
        state: present
      register: result
      delegate_to: localhost
      when:
        - result.NetworkPools | length > 0

    - name: print network pool details
      ansible.builtin.debug:
        var: result
```

**Execution:**
```
(virtualenv) [user@W11HQSX2T3 powerscale]$ ansible-navigator run network_pool.yml -i hosts

PLAY [powerscale] **************************************************************

TASK [get network pool details] ************************************************
ok: [192.168.10.20 -> localhost]

TASK [get details about the first network pool] ********************************
ok: [192.168.10.20 -> localhost]

TASK [print network pool details] **********************************************
ok: [192.168.10.20] => {
    "result": {
        "changed": false,
        "diff": null,
        "failed": false,
        "network_pool": {
            "pools": [
                {
                    "access_zone": "System",
                    "addr_family": "ipv4",
                    "aggregation_mode": "lacp",
                    "alloc_method": "static",
                    "description": "pool name description",
                    "firewall_policy": "default_pools_policy",
                    "groupnet": "groupnet0",
                    "id": "groupnet0.subnet0.pool0",
                    "ifaces": [
                        {
                            "iface": "ext-2",
                            "lnn": 1
                        },
                        {
                            "iface": "ext-2",
                            "lnn": 2
                        },
                        {
                            "iface": "ext-2",
                            "lnn": 3
                        }
                    ],
                    "ipv6_perform_dad": false,
                    "name": "pool0",
                    "nfsv3_rroce_only": false,
                    "ranges": [
                        {
                            "high": "192.168.10.22",
                            "low": "192.168.10.20"
                        }
                    ],
                    "rebalance_policy": "auto",
                    "rules": [],
                    "sc_auto_unsuspend_delay": 0,
                    "sc_connect_policy": "round_robin",
                    "sc_dns_zone": "",
                    "sc_dns_zone_aliases": [
                        "Test1",
                        "Test"
                    ],
                    "sc_failover_policy": "round_robin",
                    "sc_subnet": "",
                    "sc_suspended_nodes": [],
                    "sc_ttl": 0,
                    "static_routes": [],
                    "subnet": "subnet0"
                }
            ]
        }
    }
}

PLAY RECAP *********************************************************************
192.168.10.20              : ok=3    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```
