### ISSUE TITLE
[BUG]: SMB share get details module error

### ISSUE THREAD

**Issue by skmahankali** [dell/ansible-powerscale#138]
**Describe the bug**
I am trying to use the Ansible module “dellemc.powerscale.smb” to fetch the details of an already existing SMB share in the isilon system. When I try to execute the module, it is trying to create an SMB share instead of just getting me the details of the smb share by the name. 

Ansible module 
- name: Get SMB share details 
dellemc.powerscale.smb: 
  
  
  it says path is required

**Comment by sachin-apa** [comment]
@skmahankali The design of making configuration modules return information only is wrong. 
We recommend to use info module to get the SMB share details. Following is the example
```
 - name: Get list of smb shares from the PowerScale cluster
      dellemc.powerscale.info:
        onefs_host: "{{ onefs_host }}"
        verify_ssl: "{{ verify_ssl }}"
        api_user: "{{ api_user }}"
        api_password: "{{ api_password }}"
        access_zone: "{{ access_zone }}"
        gather_subset:
          - smb_shares
```

Please let me know if we are good to close this issue.
