### ISSUE TITLE
[BUG]: Get Details of SyncIQ Policy fails with:  Invalid value for `snapshot_sync_pattern`, length must be greater than or equal to `1`"

### ISSUE THREAD

**Issue by davisglenn** [dell/ansible-powerscale#14]
**Describe the bug**
All I am trying to do is get the Details of a SyncIQ policy.  I followed the Example in the Repo.
I get an error saying:
**_"msg": "Get details of SyncIQ policy AutomationRecovery failed with error : Invalid value for `snapshot_sync_pattern`, length must be greater than or equal to `1`"_**

**To Reproduce**
1. Step 1 - create the playbook with the values

```
  - name: Get SyncIQ policy details
     dellemc.powerscale.dellemc_powerscale_synciqpolicy:
      onefs_host: "{{ dr_onefs_host }}"
      api_user: "{{ dr_api_user }}"
      api_password: "{{ dr_api_password }}"
      verify_ssl: "{{ verify_ssl }}"
      policy_name: "AutomationRecovery"
      snapshot_sync_pattern: "*file*"
      state: "present"
    register: result
```

2. Step 2 - Run the playbook
3. Step 3 - See error

**Expected behavior**
I expect the Playbook not to fail  and the details to be available in the register variable.

**System Information (please complete the following information):**
 - OS/Version: RHEL 8.3
 - Ansible Version: 2.9.6
 - Python Version 3.6.8  

**Additional Info**
I tried this without the snapshot_sync_pattern as well since this is only doing a GET Details there should be no other information needed other than the Policy Name.
Also, NONE of the other modules work in the Examples shown in the Repo.

Lastly, the REST API Calls all work.
It would be great if the Ansible modules could use the REST API calls instead of the Python Modules.  In this case you would not need to install the Python modules.

Thanks for your help!
glenn.
