### ISSUE TITLE
[BUG]: "Error '>' not supported between instances of 'str' and 'int' while determining if Quotas are modified "

### ISSUE THREAD

**Issue by thanos-k** [dell/ansible-powerscale#16]
**Describe the bug**
 Task fails when using dict to define vars with the following error:
 "Error '>' not supported between instances of 'str' and 'int' while determining if Quotas are modified "

**To Reproduce**

Create simple playbook 

    - name: Create Filesystem with Quota in given access zone
      dellemc_powerscale_filesystem:
        onefs_host: "{{ onefs_host }}"
        port_no: "{{ port_no }}"
        verify_ssl: false
        api_user: "{{ api_user }}"
        api_password: "{{ api_password }}"
        path: "{{ item.path }}"
        access_zone: "{{ item.access_zone }}"
        quota:
          hard_limit_size: "{{ item.hard_limit_size }}"
          cap_unit: GB
          quota_state: present
        recursive: true
        state: present
      loop: "{{ filesystem }}"
      delegate_to: localhost

and host_vars like

```
filesystem:
- path: test_path
  access_zone: zn-1
  hard_limit_size: 3
  state: present

```

**System Information (please complete the following information):**
 - OS/Version: Centos 7.6
 - Ansible Version 2.9.27
 - Python Version 3.6.8 
 - dellemc.powerscale 1.4.0

**Comment by anupamaloke** [comment]
@thanos-k, could you please share the output of the ansible-playbook run?

**Comment by thanos-k** [comment]
Ooops sorry @anupamaloke 
```
ailed: [isilon -> localhost] (item={'path': 'test_d', 'access_zone': 'zn-1', 'hard_limit_size': 3, 'state': 'present'}) => {
    "ansible_loop_var": "item",
    "changed": false,
    "invocation": {
        "module_args": {
            "access_control": "777",
            "access_zone": "zn-1",
            "api_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "api_user": "root",
            "group": null,
            "list_snapshots": false,
            "onefs_host": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "owner": {
                "name": "******************",
                "provider_type": "ads"
            },
            "path": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port_no": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "quota": {
                "cap_unit": "GB",
                "hard_limit_size": "3",
                "include_data_protection_overhead": true,
                "include_snap_data": true,
                "quota_state": "present",
                "soft_limit_size": 2
            },
            "recursive": true,
            "state": "present",
            "verify_ssl": false
        }
    },
    "item": {
        "access_zone": "zn-1",
        "hard_limit_size": 3,
        "path": "test_d",
        "state": "present"
    },
    "msg": "Error '>' not supported between instances of 'str' and 'int' while determining if Quotas are modified "
}

```

**Comment by kuttattz** [comment]
@thanos-k ,
The issue is that 'hard_limit_size' is taken as string instead of int in module. This occurred because of the looping in playbook. This is an issue from ansible. 
A ticket for a similar issue is available in ansible community "https://github.com/ansible/ansible/issues/59732#issuecomment-791484225".
Giving a direct value instead of looping will avoid this issue. Another workaround is by providing complete dict in qouta parameter as mentioned below:

```
- name: Create Filesystem with Quota in given access zone
  dellemc_powerscale_filesystem:
    onefs_host: "{{ onefs_host }}"
    port_no: "{{ port_no }}"
    verify_ssl: false
    api_user: "{{ api_user }}"
    api_password: "{{ api_password }}"
    path: "{{ item.path }}"
    access_zone: "{{ item.access_zone }}"
    quota: "{{ item.quota }}"
    recursive: true
    state: present
  loop: "{{ filesystem }}"
  delegate_to: localhost

filesystem:
  - quota:
	  hard_limit_size: 3
	  cap_unit: "GB"
	  quota_state: "present"
    path: "test_path"
    access_zone: "zn-1"
    state: "present"
```
	
	
We will discuss about it and if needed take it to our backlog
