### ISSUE TITLE
[BUG]: Wrong owner set when creating directory with dellemc.powerscale.filesystem

### ISSUE THREAD

**Issue by eschek87** [dell/ansible-powerscale#174]
**Describe the bug**
If I create a new directory with module dellemc.powerscale.filesystem and set access_zone to a custom access zone (not default "System") and specify a owner with provider_type: 'ads' then a wrong owner is set (wrong active directory user).

**To Reproduce**
Module run which sets wrong owner:
```
- name: Create folder and quota
  dellemc.powerscale.filesystem:
    onefs_host: "{{ onefs_host }}"
    verify_ssl: false
    api_user: "{{ isilon_user }}"
    api_password: "{{ isilon_password }}"
    path: "/sync-on/users/Username/"
    access_zone: "Custom-Zone"
    owner:
      name: 'Username@abc.de'
      provider_type: 'ads'
    group:
      name: 'Administrators'
      provider_type: 'local'
    quota:
      include_snap_data: false
      include_data_protection_overhead: false
      hard_limit_size: 2
      cap_unit: "GB"
      quota_state: "present"
      container: true
    recursive: true
    state: "present"
```

Module run which sets correct owner:
```
- name: Create folder and quota
  dellemc.powerscale.filesystem:
    onefs_host: "{{ onefs_host }}"
    verify_ssl: false
    api_user: "{{ isilon_user }}"
    api_password: "{{ isilon_password }}"
    path: "/ifs/folder/sync-on/users/Username/"
    access_zone: "System"
    owner:
      name: 'Username@abc.de'
      provider_type: 'ads'
    group:
      name: 'Administrators'
      provider_type: 'local'
    quota:
      include_snap_data: false
      include_data_protection_overhead: false
      hard_limit_size: 2
      cap_unit: "GB"
      quota_state: "present"
      container: true
    recursive: true
    state: "present"
```
**Expected behavior**
Correct active directory user is set as owner

**Screenshots**

**Logs**
If applicable, submit logs or stack traces from the affected services

**System Information (please complete the following information):**
 - OS/Version: Red Hat 8.5
 - Ansible Version: 2.16.14
 - Python Version: 3.11.11 
 - isilon-sdk==0.4.0
 - OneFS Version: 9.5.0.8

**Additional context**
If I run the same on a onefs simulator cluster with 9.2.1.0 it works.
