### ISSUE TITLE
[BUG]: File System module fails to modify ACL rights for a trustee from any zone except System

### ISSUE THREAD

**Issue by Bonifucksy** [dell/ansible-powerscale#33]
**Describe the bug**
When trying to modify ACL rights for a trustee from any zone except System the task fails with message:
`Setting ACL rights of Filesystem ifs/testzone/zoneinsidezone/zoneinsidezoneinsidezone/shareFSmoduletest5 failed with error:  { errors : [ { code : AEC_BAD_REQUEST , message : Invalid trustee } ] }`
But it works fine when I specify a user from System zone.

**To Reproduce**
1. Step 1 create additional zone / in my case:
```
ISILONSIMULATOR-1# isi zone list -v
                       Name: zoneinsidezoneinsidezone
                       Path: /ifs/testzone/zoneinsidezone/zoneinsidezoneinsidezone
                   Groupnet: groupnet0
              Map Untrusted:
             Auth Providers: lsa-file-provider:System, lsa-local-provider:zoneinsidezoneinsidezone
               NetBIOS Name:
         User Mapping Rules: -
       Home Directory Umask: 0077
         Skeleton Directory: /usr/share/skel
         Cache Entry Expiry: 4H
Negative Cache Entry Expiry: 1m
                    Zone ID: 4
```

2. Step 2 create a user in that zone / in my case:
```
ISILONSIMULATOR-1# isi auth users list --zone zoneinsidezoneinsidezone
Name
lvl3user
anotheruser
```

3. Step 3 run File System module to create a directory for the zone and the first user from above and to assign ACL rights for the second user from above (it also fails with the same error if I separate the directory creation and the ACL rights assignment to different tasks):
```
- name: create a directory and assign target permissions in the corresponding zone
  dellemc.powerscale.filesystem:
    onefs_host: "{{onefs_host}}"
    verify_ssl: "{{verify_ssl}}"
    api_user: "{{api_user}}"
    api_password: "{{api_password}}"
    path: "/shareFSmoduletest6"
    access_zone: "zoneinsidezoneinsidezone"
    owner:
      name: 'lvl3user'
      provider_type: 'LOCAL:zoneinsidezoneinsidezone'
    access_control_rights:
      access_type: "allow"
      access_rights:
          - dir_gen_all
      inherit_flags:
          - container_inherit
      trustee: 'anotheruser3'
    access_control_rights_state: "add"
    state: "present"
```

**Expected behavior**
ACL rights from the task should be assigned to the second user (anotheruser3).

**Logs**
The full output:
```
fatal: [ISILONSIMULATOR]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "access_control": null,
            "access_control_rights": {
                "access_rights": [
                    "dir_gen_all"
                ],
                "access_type": "allow",
                "inherit_flags": [
                    "container_inherit"
                ],
                "trustee": "anotheruser3"
            },
            "access_control_rights_state": "add",
            "access_zone": "zoneinsidezoneinsidezone",
            "api_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "api_user": "root",
            "group": null,
            "list_snapshots": false,
            "onefs_host": "DBISILONSIMULATOR",
            "owner": {
                "name": "lvl3user",
                "provider_type": "LOCAL:zoneinsidezoneinsidezone"
            },
            "path": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port_no": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "quota": null,
            "recursive": true,
            "recursive_force_delete": false,
            "state": "present",
            "verify_ssl": false
        }
    },
    "msg": "Setting ACL rights of Filesystem ifs/testzone/zoneinsidezone/zoneinsidezoneinsidezone******** failed with error:  { errors : [ { code : AEC_BAD_REQUEST , message : Invalid trustee } ] } "
```

But the directory still gets created. Without the second user ACL rights though:
```
ISILONSIMULATOR-1# ls -led /ifs/testzone/zoneinsidezone/zoneinsidezoneinsidezone/shareFSmoduletest6
drwx------     2 lvl3user  wheel  0 Aug  3 17:57 /ifs/testzone/zoneinsidezone/zoneinsidezoneinsidezone/shareFSmoduletest6
 OWNER: user:lvl3user
 GROUP: group:wheel
 SYNTHETIC ACL
 0: user:lvl3user allow dir_gen_read,dir_gen_write,dir_gen_execute,std_write_dac,delete_child
 1: group:wheel allow std_read_dac,std_synchronize,dir_read_attr
```

**System Information (please complete the following information):**
 - OS/Version: Ubuntu 20.04.4 LTS
 - Ansible Version: 2.13.2
 - Python Version: 3.9.13  
 - OneFS version: 9.2.1.10
