### ISSUE TITLE
[FEATURE]: S3 Bucket support

### ISSUE THREAD

**Issue by MelvinSone** [dell/ansible-powerscale#55]
The project dosen't support a S3 bucket configuration.

**Comment by anupamaloke** [comment]
@MelvinSone , thank you for submitting the feature request. Could you please provide a little more detail about the PowerScale version details that you are running? Also, from a S3 bucket configuration point of view, what are the key use-cases that you are looking to automate using ansible? These details would help us in prioritizing this accordingly for future releases.

**Comment by MelvinSone** [comment]
@anupamaloke oh sorry for the few information. Im running the latest Version of Dell's Powerscale. I wanted to automate the S3 Buckets, so that i can have different Buckets for my Kubernetes cluster. Right now we do it manually over the UI and its a bit slow in the process. And it would be better if we have our whole Powerscale in a IaC ansible role or playbook, for disaterrecovery.  This is why i searched for an ansible-galaxy collection and found Dell Powerscale, but the S3 Bucket feature was missing this is the biggest part we're using on the Powerscale.

**Comment by anupamaloke** [comment]
@MelvinSone, thank you for sharing the details. I have added it to our backlog that we will prioritize and deliver over the next couple of releases. Just to reconfirm my understanding, following are the key features that you are looking to automate using ansible modules:
- create S3 buckets
- modify S3 buckets
- delete S3 buckets   

Also, are you looking for following S3 functionality as well to be supported with ansible:
- Generate a secret key/access ID for a given user
- S3 global configuration settings as well as for a zone

**Comment by MelvinSone** [comment]
@anupamaloke You're right, i'm looking for all of the features you listed. Thanks for the fast reply. can't wait for the new Version of this ansible collection.

**Comment by anupamaloke** [comment]
@MelvinSone, S3 support is now available with v2.1.0 of the collection. Please checkout [s3_bucket](https://github.com/dell/ansible-powerscale/blob/main/plugins/modules/s3_bucket.py) module

```
- name: Create S3 Bucket
  dellemc.powerscale.s3_bucket:
    onefs_host: "{{onefs_host}}"
    api_user: "{{api_user}}"
    api_password: "{{api_password}}"
    verify_ssl: "{{verify_ssl}}"
    s3_bucket_name: "Anisble_S3_bucket"
    path: "/sample_bucket_path"
    access_zone: "sample-zone"
    owner: "sample-user"
    description: "the S3 bucket created."
    object_acl_policy: "replace"
    acl:
      - permission: "READ"
        grantee:
          name: "everyone"
          type: "wellknown"
      - permission: "READ_ACL"
        grantee:
          name: "sample-user"
          type: "user"
          provider_type: "local"
        acl_state: "present"
    state: "present"
```
